In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.neighbors import NearestNeighbors

In [2]:
x = np.random.normal(0,1,[4096,30000])
x.shape

(4096, 30000)

In [3]:
y = euclidean_distances(x, x)
y.shape

(4096, 4096)

In [4]:
y

array([[   0.        ,  245.61521346,  245.22909192, ...,  244.73856012,
         244.94846637,  243.02933638],
       [ 245.61521346,    0.        ,  243.71982766, ...,  244.02752618,
         244.35624298,  243.48864172],
       [ 245.22909192,  243.71982766,    0.        , ...,  244.11235981,
         245.882992  ,  244.14396657],
       ..., 
       [ 244.73856012,  244.02752618,  244.11235981, ...,    0.        ,
         244.48707071,  242.2181134 ],
       [ 244.94846637,  244.35624298,  245.882992  , ...,  244.48707071,
           0.        ,  243.69535625],
       [ 243.02933638,  243.48864172,  244.14396657, ...,  242.2181134 ,
         243.69535625,    0.        ]])

In [24]:
nbrs = NearestNeighbors(n_neighbors=4,metric='euclidean').fit(x)

In [ ]:
NearestNeighbors?

In [25]:
distances, indices = nbrs.kneighbors(x)

In [27]:
indices

array([[   0,  225],
       [   1,   70],
       [   2, 2169],
       ..., 
       [4093,  236],
       [4094, 3923],
       [4095, 1585]])

In [21]:
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
nbrs = NearestNeighbors(n_neighbors=6,metric='euclidean').fit(X)

In [22]:
distances, indices = nbrs.kneighbors(X)

In [23]:
distances

array([[ 0.        ,  1.        ,  2.23606798,  2.82842712,  3.60555128,
         5.        ],
       [ 0.        ,  1.        ,  1.41421356,  3.60555128,  4.47213595,
         5.83095189],
       [ 0.        ,  1.41421356,  2.23606798,  5.        ,  5.83095189,
         7.21110255],
       [ 0.        ,  1.        ,  2.23606798,  2.82842712,  3.60555128,
         5.        ],
       [ 0.        ,  1.        ,  1.41421356,  3.60555128,  4.47213595,
         5.83095189],
       [ 0.        ,  1.41421356,  2.23606798,  5.        ,  5.83095189,
         7.21110255]])

In [17]:
y = euclidean_distances(X, X)
y

array([[ 0.        ,  1.        ,  2.23606798,  2.82842712,  3.60555128,
         5.        ],
       [ 1.        ,  0.        ,  1.41421356,  3.60555128,  4.47213595,
         5.83095189],
       [ 2.23606798,  1.41421356,  0.        ,  5.        ,  5.83095189,
         7.21110255],
       [ 2.82842712,  3.60555128,  5.        ,  0.        ,  1.        ,
         2.23606798],
       [ 3.60555128,  4.47213595,  5.83095189,  1.        ,  0.        ,
         1.41421356],
       [ 5.        ,  5.83095189,  7.21110255,  2.23606798,  1.41421356,
         0.        ]])